### ISSUE TITLE
Thoughts on validating query params

### ISSUE THREAD

**Issue by cyberwombat** [stearm/micro-joi#4]
I see that this only works for body. What's the reasoning for not validating query params? Open to exploring that?

**Comment by stearm** [comment]
Hi @cyberwombat! There isn't a reason, I did not need it. But if you want you can open a PR or I can code it for you 👍

**Comment by cyberwombat** [comment]
Cool. I made a mod for myself that has body/query support by specifying it in the schema:

    {
       body: Joi...
       quey: Joi...
    }

That does make it backward incompatible. Could make it fallback to body if not specified if that was desired.

**Comment by stearm** [comment]
I created a new branch called "url_validation" with an implementation of your request. If you want, you can try it @cyberwombat :)

**Comment by cyberwombat** [comment]
Thanks! So it works but only with an older Joi - I see you have v 10.x. I use 13.x and it fails. Downgrading back to 10 works. Not sure why off hand. They do now use the `object().keys({})` format but that did not seem to make a diff. Something about the hoek reach command I think.

**Comment by stearm** [comment]
Yep I see also that new version of Joi use node 8. Do you have any idea how to procede? Maybe I can release this version as patch, then release a new version with breaking change which use Joi v13. What do you think about it?

**Comment by cyberwombat** [comment]
I think thats a good idea. I am all for moving forward.

**Comment by stearm** [comment]
@cyberwombat I just released 3.0.0 which use latest version of Joi! 😄

**Comment by cyberwombat** [comment]
Sweet!  Works great. Thanks for coding that so quickly!

**Comment by stearm** [comment]
Your welcome! Thanks for the idea!
