### ISSUE TITLE
Maintain query data from joi into handler

### ISSUE THREAD

**Issue by cyberwombat** [stearm/micro-joi#5]
Joi has the ability to transform data - for example it automatically casts 'true' as true. However micro-joi only validates but doesn't overwrite the original query like it does with the body. Would that be possible?

**Comment by cyberwombat** [comment]
I've added `req.query = result.value` in the code and that seems to work fine though I don't know of potential issues.

**Comment by stearm** [comment]
Hi @cyberwombat! Thanks for the PR, I just merged it and published to NPM. 🚀
